version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./data/contour_intermediate:/code/data
    ports:
      - "8080:80"
  elevation:
    image: openelevation/open-elevation
    volumes:
      - ./data:/code/data
    ports:
      - "8000:8080"
