version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./data/:/code/data
      - ./app:/code/app
    ports:
      - "8080:80"

  open-elevation:
    image: openelevation/open-elevation
    volumes:
      - ./data/open_elevation_data:/code/data
    ports:
      - "8000:8080"
