version: "3"
services:
  permacultr-api:
    build:
      context: ./permacultr_api
      dockerfile: Dockerfile
    volumes:
      - ./data/:/code/data
      - ./permacultr_api/app:/code/app
    ports:
      - "8080:80"

  open-elevation:
    image: openelevation/open-elevation
    volumes:
      - ./data/open_elevation_data:/code/data
    ports:
      - "8000:8080"

  osm-api:
    build:
      context: ./osm_api
      dockerfile: Dockerfile
    volumes:
      - ./osm_api/app:/code/app
    ports:
      - "8090:80"
